services:
  app:
    container_name: resource-service
    image: resource-service-img
    build: ./
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgresql_resource_service
  postgresql_resource_service:
    container_name: postgresql_resource_service
    image: postgres-resource-service
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=resource_service_db
