server:
  port: 8082
spring:
  datasource:
    url: 'jdbc:postgresql://postgresql_resource_service:5432/resource_service_db'
    driver-class-name: 'org.postgresql.Driver'
    username: 'postgres'
    password: 'root'
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 20MB
      max-request-size: 25MB

cloud:
  aws:
    credentials:
      access-key: AKIAZ5BIJKHEKH3BB64N
      secret-key: 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
#    region: us-east-1
#    endpoint: http://localhost:4566
    bucket:
      name: va-resource-service